apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      nodeName: node2.demo1.rtcontainer-pg0.wisc.cloudlab.us
      containers:
      - name: vdc
        image: kaobinchou/virtual-device-callback:latest  # Replace with your Docker image name
        ports:
        - containerPort: 3000
        securityContext:
          privileged: true
